SCREEN_WIDTH = 660
SCREEN_HEIGHT = 660
SCREEN_TITLE = "Bomberman"
CELL_WIDTH = 60
CELL_HEIGHT = 60
ROW_COUNT = 11
COLUMN_COUNT = 11
PLAYER_ONE_SPEED = 10
PLAYER_TWO_SPEED = 10

PLAYER_ONE_BOMB_COUNT = 1
PLAYER_TWO_BOMB_COUNT = 1
